version: '3.8'

services:
  clickup-mcp:
    build: .
    container_name: clickup-mcp
    env_file:
      - .env
    ports:
      - "8080:8080"   # HTTP Streamable endpoint at /mcp
    restart: unless-stopped
    networks:
      - default
      - shared_n8n

networks:
  shared_n8n:
    external: true
    name: n8n-ai-local_shared_n8n_network
